title:            The Machine Hearts
description:      Describe your website here.
disqus_shortname: shortname
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
#url: ""
url:              "http://www.themachinehearts.com"
# Owner/author information
owner:
  name:           The Machine Hearts
  avatar:         the-machine-hearts.png
  bio:            "We think too much, but feel too little."
  #email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  #twitter:        
  #facebook:       
  #github:         
  #stackexchange:  
  #linkedin:       
  #instagram:      
  #flickr:         
  #tumblr:         
  ## google plus id, include the '+', eg +mmistakes
  #google_plus:    +yourid

# Analytics and webmaster tools stuff goes here
google_analytics: UA-71842199-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
